# Generated by Django 4.2 on 2025-12-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Rules', max_length=100)),
                ('base_score', models.IntegerField(default=10)),
                ('image_bonus', models.IntegerField(default=5)),
                ('long_description_bonus', models.IntegerField(default=3)),
                ('urgent_keyword_bonus', models.IntegerField(default=10)),
                ('overdue_penalty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='submitted', max_length=30)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='accounts.municipalstaff')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.resident')),
                ('rule_config', models.ForeignKey(blank=True, help_text='Rules used to calculate priority.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ruleconfig')),
            ],
            options={
                'ordering': ['-priority_score', 'created_at'],
            },
        ),
    ]
